version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: sudo npm install jest --global
            - run: npm run client::build
            - run: npm run test
            - run: ./node_modules/.bin/codecov --token=bb75ab81-b362-41ec-ba14-0d25bfb33fd3
workflows:
    build-and-test:
      jobs:
        - build-and-test
